site_name: Retroinformática
nav:
    - Inicio: index.md
    - Ordenadores años 60: pc_anos60.md
    - Ordenadores años 70: pc_anos70.md
    - Ordenadores años 80: pc_anos80.md
    - Creación de footer: about.md
theme: amelia